{{- if and .Values.modules.server.enabled }}
{{- $mod := dict "root" . "name" "server" "component" "server" "module" .Values.modules.server -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
    {{- include "trustification.application.annotations" $mod | nindent 4 }}

spec:
  replicas: {{ include "trustification.application.replicas" $mod }}
  selector:
    matchLabels:
      {{- include "trustification.common.selectorLabels" $mod | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustification.common.selectorLabels" $mod | nindent 8 }}
        {{- include "trustification.application.podLabels" $mod | nindent 8 }}
      annotations:
        configHash/auth: {{ include (print $.Template.BasePath "/services/server/020-ConfigMap-auth.yaml") . | sha256sum }}

    spec:
      {{- include "trustification.application.pod" $mod | nindent 6 }}

      containers:
        - name: service
          {{- include "trustification.common.defaultImage" $mod | nindent 10 }}
          {{- include "trustification.application.container" $mod | nindent 10 }}
          {{- include "trustification.application.infrastructure.probes" $mod | nindent 10 }}

          command: [ "/usr/local/bin/trustd" ]
          args:
            - api
            - --auth-configuration
            - "/etc/config/auth.yaml"
            - --working-dir
            - "/data/workdir"

          env:

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            {{- include "trustification.application.rust.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.infrastructure.envVars" $mod | nindent 12 }}
            {{- include "trustification.application.httpServer.envVars" $mod | nindent 12 }}
            {{- include "trustification.postgres.envVars" (dict "root" . "database" .Values.database) | nindent 12 }}
            {{- include "trustification.storage.envVars" $mod | nindent 12 }}
            {{- include "trustification.oidc.swaggerUi" $mod | nindent 12 }}

            - name: UI_ISSUER_URL
              value: {{ include "trustification.oidc.frontendIssuerUrl" . }}
            - name: UI_CLIENT_ID
              value: {{ include "trustification.oidc.frontendClientId" . }}

            {{- with $mod.module.analyticsWriteKey }}
            - name: UI_ANALYTICS_WRITE_KEY
              value: {{ . | quote }}
            {{- end }}

            {{- with $mod.module.uploadLimit }}
            - name: TRUSTD_SBOM_UPLOAD_LIMIT
              value: {{ include "trustification.common.byteSizeValue" . }}
            - name: TRUSTD_ADVISORY_UPLOAD_LIMIT
              value: {{ include "trustification.common.byteSizeValue" . }}
            - name: TRUSTD_DATASET_ENTRY_LIMIT
              value: {{ include "trustification.common.byteSizeValue" . }}
            {{- end }}

            {{/* FIXME: adapt env-var */}}
            {{- if eq ( include "trustification.openshift.useServiceCa" .root ) "true" }}
            - name: CLIENT_TLS_CA_CERTIFICATES
              value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            {{- end }}

          ports:
            {{- include "trustification.application.infrastructure.podPorts" $mod | nindent 12 }}
            - containerPort: 8080
              name: endpoint
              protocol: TCP

          volumeMounts:
            - name: workdir
              mountPath: /data/workdir
            {{- include "trustification.application.httpServerVolumesMounts" $mod | nindent 12 }}
            {{- include "trustification.authenticator.volumeMount" $mod | nindent 12 }}
            {{- include "trustification.storage.volumeMount" $mod | nindent 12 }}
            {{- include "trustification.application.extraVolumeMounts" $mod | nindent 12 }}

      volumes:
        - name: workdir
          emptyDir: {}
        {{- include "trustification.application.httpServerVolumes" $mod | nindent 8 }}
        {{- include "trustification.authenticator.volume" $mod | nindent 8 }}
        {{- include "trustification.storage.volume" $mod | nindent 8 }}
        {{- include "trustification.application.extraVolumes" $mod | nindent 8 }}

{{ end }}
