{{- if and .Values.modules.server.enabled }}
{{- $mod := dict "root" . "name" "server" "component" "server" "module" .Values.modules.server -}}
{{- include "trustification.ingress.defaultIngress" ( set (deepCopy $mod) "host" (include "trustification.host.server" $mod ) ) }}
{{- end }}
